### ISSUE TITLE
无法正确解析lqbin文件

### ISSUE THREAD

**Issue by ALDTSE** [Avenshy/MajsoulMax#20]
昨日闪彩联动更新后Avenshy的autoLiqi至今发布了两次liqi文件更新，目前最新版本为v0.11.104w，尝试使用这两次更新的lqbin文件，均提示无法正常解析，报错如下：
![9](https://github.com/user-attachments/assets/a324ba11-9385-4290-a7fb-a837935a1a36)
替换回过时的lqbin文件可正常解析并启动mod。怀疑是最新的lqc.lqbin文件的问题。

**Comment by Avenshy** [comment]
@ALDTSE 请同时更新其他文件

**Comment by ALDTSE** [comment]
proto文件夹下的其他文件均已更新至最新release版本。

**Comment by Avenshy** [comment]
[https://github.com/Xerxes-2/AutoLiqi/releases/latest](https://github.com/Xerxes-2/AutoLiqi/releases/latest)
下载这里的lqc.lqbin，覆盖proto文件夹下同名文件

**Comment by ALDTSE** [comment]
问题已解决，感谢！
