### ISSUE TITLE
运行run后显示一串代码，打开网页无效果

### ISSUE THREAD

**Issue by cmm147369** [Avenshy/MajsoulMax#22]
![run_CLhpqohevV](https://github.com/user-attachments/assets/33e09ac9-d1e5-48f5-b8fa-7a0831438d65)
我只在网页上运行雀魂，没有用[Proxifier]，我看到楼下有个兄弟是端口填错了，我跟他错误名相同，网上查这串代码说是defender删除了程序，为了避免是杀毒软件的问题，我已经完全卸载了windows defender，还是没有效果，求大佬帮我看一下我是哪里出了问题，十分感谢

**Comment by Avenshy** [comment]
@2673748705 max运行正常，是浏览器问题，没有转发到max

**Comment by cmm147369** [comment]
> @2673748705 max运行正常，是浏览器问题，没有转发到max

感谢大佬帮忙，我重新创建了一个快捷方式，问题就解决了
