### ISSUE TITLE
没有最新的几个角色的皮肤

### ISSUE THREAD

**Issue by guardianaa** [Avenshy/MajsoulMax#24]
作者大大好，用的steam版，proto文件夹内的几个文件也手动更新了，最新的几个角色还是只显示一姬
![image](https://github.com/user-attachments/assets/55909035-72e5-4e3a-bf49-ad9856d3bbc4)
![image](https://github.com/user-attachments/assets/91d73d47-5ab2-4660-b72c-6d1499681b69)
![image](https://github.com/user-attachments/assets/33cd9085-0f3a-4ba6-86b3-b66c0af65332)

**Comment by Avenshy** [comment]
@guardianaa 配置乱了，删除mod配置重新运行即可

**Comment by guardianaa** [comment]
> @guardianaa 配置乱了，删除mod配置重新运行即可

选皮肤那里选了其他的皮肤就刷出来了，不知道怎么回事
