### ISSUE TITLE
请问如何修改代码？

### ISSUE THREAD

**Issue by StackExplode** [Avenshy/MajsoulMax#25]
我想自己修改代码，添加自己的逻辑，但是修改了mod.py后并不生效。
我没有从事过py开发，但是读代码还是能大概读懂，还请不吝赐教，谢谢。

**Comment by Avenshy** [comment]
请使用源码运行

**Comment by StackExplode** [comment]
> 请使用源码运行

请问入口点在哪个文件呢？我看好多文件都带main。

**Comment by Avenshy** [comment]
@StackExplode 😓😓😓😓😓

> 雀魂解锁全角色、皮肤、装扮等，基于mitmproxy的中间人攻击方式，支持网页版和客户端/Steam端。

请先学习mitmproxy基础知识

**Comment by StackExplode** [comment]
> @StackExplode 😓😓😓😓😓
> 
> > 雀魂解锁全角色、皮肤、装扮等，基于mitmproxy的中间人攻击方式，支持网页版和客户端/Steam端。
> 
> 请先学习mitmproxy基础知识

好的，谢谢指导。
